# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b0bebc0f54cef346ff18a9869f21c4913d68a0e74b7e21fefcb93a1af3b9afee82014954f9da872af3ded2005e9de612b28bcdd6437dff88234bf60709d7c7

test:
  secret_key_base: ec314a576108d1b0f09113e6c954b2e75d19f648bbb5d9a1b5f082caebc8b40ff38b5f8c90e4c3a2075707ea4de706b660809d5f71110abccbb3ff54ca257c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
